# Generated by Django 3.2.7 on 2021-10-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_auto_20211007_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='DOB',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='desc',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='name1',
            new_name='name',
        ),
    ]
