# Generated by Django 3.2.7 on 2021-10-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0004_alter_movie_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='DOB',
        ),
        migrations.AddField(
            model_name='movie',
            name='Age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='Phone',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
